const data = [
  {
    id: 1,
    title: "Kalanchoe Tomentosa",
    url: "kalanchoe_tomentosa.html",
    category: "suculenta",
    price: "Vendida",
    img: "../plantas/img/planta1_1.jpg",
    img2: "../plantas/img/planta1_2.jpg",
    img3: "../plantas/img/planta1_3.jpg",
    desc:
      "Popularmente conocida como Oreja de Panda. Es una suculenta bien resistente, fácil de cultivar tanto en interiores como exteriores.",
    care:
      "Necesitan una exposición a pleno sol y, gracias a sus pelillos, resisten bien la insolación. No le convienen temperaturas inferiores a 8 ºC, siendo su temperatura ideal en invierno de unos 10 ºC. El calanchoe aterciopelado se cultivará en un suelo formado, a partes iguales, de turba, arena y mantillo. Son plantas resistentes a la sequía que sólo necesitan un moderado riego semanal durante todo el año, menos en invierno que será cada 2 semanas.",
  },
  {
    id: 2,
    title: "Echeveria Cuspidata",
    url: "echeveria_cuspidata.html",
    category: "suculenta",
    price: "$15",
    img: "../plantas/img/planta2_1.JPG",
    img2: "../plantas/img/planta2_2.jpg",
    img3: "../plantas/img/planta2_3.jpg",
    desc:
      "Nuestra variedad zaragozae es de mis favoritas, especialmente cuando están presentes las flores de color naranja rojizo brillante y los tallos florecientes.",
    care: " ",
  },
  {
    id: 3,
    title: "Haworthia Cymbiformis",
    url: "haworthia_cymbiformis.html",
    category: "suculenta",
    price: "Vendida",
    img: "../plantas/img/planta3_1.JPG",
    img2: "../plantas/img/planta3_2.jpg",
    img3: "../plantas/img/planta3_3.jpg",
    desc:
      'El nombre de cymbiformis significa "con forma de bote", se caracteriza por presentar hojas muy carnosas y jugosas, suaves y que se  hinchan con el agua almacenada.',
    care: " ",
  },
  {
    id: 4,
    title: "Crassula Ovata Variegata",
    url: "crassula_ovata_variegata.html",
    category: "suculenta",
    price: "$20",
    img: "../plantas/img/planta4_1.JPG",
    img2: "../plantas/img/planta4_2.jpg",
    img3: "../plantas/img/planta4_3.jpg",
    desc:
      'Conociada como "árbol de jade", característico por sus hojas carnosas y su forma de arbolito, su resistencia a sequías la hace una buena especie para principiantes.',
    care: " ",
  },
  {
    id: 5,
    title: "Kalanchoe Fedtschenkoi",
    url: "kalanchoe_fedtschenkoi.html",
    category: "suculenta",
    price: "Vendida",
    img: "../plantas/img/planta5_1.JPG",
    img2: "../plantas/img/planta5_2.jpg",
    img3: "../plantas/img/planta5_3.jpg",
    desc:
      "Se caracterizan por abrir sus flores haciendo crecer nuevas células en la superficie interior de los pétalos para forzarlas a salir y en la parte exterior para cerrarlas.",
    care: " ",
  },
  {
    id: 6,
    title: "Aglanomea Prosperity",
    url: "aglanomea_prosperity.html",
    category: "ornamental",
    price: "Vendida",
    img: "../plantas/img/planta6_1.JPG",
    img2: "../plantas/img/planta6_2.jpg",
    img3: "../plantas/img/planta6_3.jpg",
    desc:
      "Esta es una hermosa planta de interior, tiene un hermoso color verde con hojas rojas con manchas y rayas llamativas. Las aglaonemas son de crecimiento lento, atractivas y son plantas de excelente follaje. Lo mejor de todo es que no le gusta el sol directo, por lo que es perfecta para interiores.",
    care: " ",
  },
  {
    id: 7,
    title: "Parodia Ottonis",
    url: "parodia_ottonis.html",
    category: "cacti",
    price: "$15",
    img: "../plantas/img/planta7_1.JPG",
    img2: "../plantas/img/planta7_2.JPG",
    img3: "../plantas/img/planta7_3.JPG",
    desc:
      "Caracterizados por tener flores de colores vibrantes, como son el amarillo, el naranja y el rojo. Estamos frente a un género especial para principiantes. Son cactus fáciles de mantener en maceta, pero siempre teniendo en cuenta los consejos básicos.",
    care: " ",
  },
  {
    id: 8,
    title: "Graptosedum “Bronze”",
    url: "graptosedum_bronze.html",
    category: "suculenta",
    price: "$12",
    img: "../plantas/img/planta8_1.JPG",
    img2: "../plantas/img/planta8_2.JPG",
    img3: " ",
    desc: "Cualquier cosa. ",
    care: "Otra cosa. ",
  },
  {
    id: 9,
    title: "Echeveria “Topsy Turvy”",
    url: "echeveria_topsy_turvy.html",
    category: "suculenta",
    price: "Vendida",
    img: "../plantas/img/planta9_1.JPG",
    img2: "../plantas/img/planta9_2.JPG",
    img2: " ",
    img3: " ",
    desc:
      "Una espléndida planta que se desarrolla de manera sencilla y rápida. Tiene hojas maravillosamente distorsionadas.Produce muchas rosetas nuevas en su base y no crece un tallo alto y desnudó como otros cultivos de Echeveria.",
    care: " ",
  },
  {
    id: 10,
    title: 'Echeveria "White Line"',
    url: "echeveria_white_line.html",
    category: "suculenta",
    price: "$15",
    img: "../plantas/img/planta10_1.JPG",
    img2: "../plantas/img/planta10_2.JPG",
    img3: "../plantas/img/planta10_3.JPG",
    desc: " ",
    care: " ",
  },
  {
    id: 11,
    title: "Echeveria “Hércules”",
    url: "echeveria_hercules.html",
    category: "suculenta",
    price: "Vendida",
    img: "../plantas/img/planta11_1.JPG",
    img2: " ",
    img3: " ",
    desc: " ",
    care: " ",
  },
  {
    id: 12,
    title: "Gymnocalycium Monvillei",
    url: "gymnocalycium_monvillei.html",
    category: "cacti",
    price: "$12",
    img: "../plantas/img/planta12_1.JPG",
    img2: "../plantas/img/planta12_2.JPG",
    img3: " ",
    desc: " ",
    care: " ",
  },
  {
    id: 13,
    title: "Crassula Ovata Gollum",
    url: "crassula_ovata_gollum.html",
    category: "suculenta",
    price: "$20",
    img: "../plantas/img/planta13_1.JPG",
    img2: "../plantas/img/planta13_2.JPG",
    img3: " ",
    desc: " ",
    care: " ",
  },
  {
    id: 14,
    title: "Haworthia Spiralis",
    url: "haworthia_spiralis.html",
    category: "suculenta",
    price: "$12",
    img: "../plantas/img/planta14_1.JPG",
    img2: "../plantas/img/planta14_2.JPG",
    img3: "../plantas/img/planta14_3.JPG",
    desc: " ",
    care: " ",
  },
  //   {
  //     id: 15,
  //     title: "Nuevo Cactus",
  //     url: "nuevo_cactus.html",
  //     category: "cacti",
  //     price: "$10",
  //     img: "../plantas/img/planta15_1.JPG",
  //     img2: "../plantas/img/planta15_2.JPG",
  //     img3: "../plantas/img/planta15_3.JPG",
  //     desc: "Este es un nuevo cactus blablabla ",
  //     care: "Este cactus se cuid blablabla",
  //   },
];

export { data };
